vich_uploader:
    db_driver: orm

    mappings:
        archive:
            namer:
                service: Vich\UploaderBundle\Naming\OrignameNamer
            upload_destination: '%kernel.project_dir%/public/archive'
            uri_prefix: /archive
