vich_uploader:
    db_driver: orm

    mappings:
        archive:
            namer:
                service: App\Service\ApplicationNamer
            upload_destination: '%kernel.project_dir%/public/archive'
            uri_prefix: /archive

        archive2:
            namer:
                service: App\Service\ApplicationNamer2
            upload_destination: '%kernel.project_dir%/public/archive'
            uri_prefix: /archive
